import { GameData } from '@/types';
import { formatDateRange, formatPrice } from '@/lib/utils';

/**
 * Trigger browser file download from Blob
 */
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 1. Export as JSON (Full structured backup)
 */
export function exportToJSON(games: GameData[], filename = 'epic-free-games-library.json') {
  const exportPayload = {
    version: '2.0.0',
    generatedAt: new Date().toISOString(),
    totalGames: games.length,
    totalValueUSD: games.reduce((sum, g) => sum + (g.originalPrice || 0), 0),
    claimedGameIds: games.map((g) => g.id),
    games: games.map((g) => ({
      id: g.id,
      title: g.title,
      developer: g.developer || 'Unknown',
      publisher: g.publisher || 'Unknown',
      originalPriceUSD: g.originalPrice || 0,
      giveawayStartDate: g.giveawayStartDate,
      giveawayEndDate: g.giveawayEndDate,
      giveawayType: g.giveawayType,
      storeUrl: g.storeUrl,
    })),
  };

  downloadFile(JSON.stringify(exportPayload, null, 2), filename, 'application/json;charset=utf-8');
}

/**
 * 2. Export as CSV (Standard Comma-Separated Values)
 */
export function exportToCSV(games: GameData[], filename = 'epic-free-games-library.csv') {
  const headers = [
    'ID',
    'Title',
    'Developer',
    'Publisher',
    'Original Price (USD)',
    'Giveaway Start Date',
    'Giveaway End Date',
    'Giveaway Type',
    'Store URL',
  ];

  const escapeCSV = (str: string | number | undefined | null): string => {
    if (str === undefined || str === null) return '""';
    const s = String(str).replace(/"/g, '""');
    return `"${s}"`;
  };

  const rows = games.map((g) => [
    escapeCSV(g.id),
    escapeCSV(g.title),
    escapeCSV(g.developer || 'Unknown'),
    escapeCSV(g.publisher || 'Unknown'),
    escapeCSV(g.originalPrice || 0),
    escapeCSV(g.giveawayStartDate),
    escapeCSV(g.giveawayEndDate),
    escapeCSV(g.giveawayType),
    escapeCSV(g.storeUrl),
  ]);

  const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
  downloadFile(csvContent, filename, 'text/csv;charset=utf-8');
}

/**
 * 3. Export for Microsoft Excel (.csv with UTF-8 BOM so Excel auto-parses cleanly without character encoding bugs)
 */
export function exportToExcel(games: GameData[], filename = 'epic-free-games-library-excel.csv') {
  const headers = [
    'ID',
    'Title',
    'Developer',
    'Publisher',
    'Original Price (USD)',
    'Giveaway Start Date',
    'Giveaway End Date',
    'Giveaway Type',
    'Store URL',
  ];

  const escapeCSV = (str: string | number | undefined | null): string => {
    if (str === undefined || str === null) return '""';
    const s = String(str).replace(/"/g, '""');
    return `"${s}"`;
  };

  const rows = games.map((g) => [
    escapeCSV(g.id),
    escapeCSV(g.title),
    escapeCSV(g.developer || 'Unknown'),
    escapeCSV(g.publisher || 'Unknown'),
    escapeCSV(g.originalPrice || 0),
    escapeCSV(g.giveawayStartDate),
    escapeCSV(g.giveawayEndDate),
    escapeCSV(g.giveawayType),
    escapeCSV(g.storeUrl),
  ]);

  // \uFEFF is the UTF-8 Byte Order Mark (BOM) needed by Excel
  const excelContent = '\uFEFF' + [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
  downloadFile(excelContent, filename, 'text/csv;charset=utf-8');
}

/**
 * 4. Export as SQLite (.sql script ready to execute in any database)
 */
export function exportToSQLite(games: GameData[], filename = 'epic-free-games-library.sql') {
  const lines: string[] = [
    '-- Epic Games Store Free Library SQLite Script',
    '-- Generated by freeepicgamesdotgg',
    `-- Date: ${new Date().toISOString()}`,
    '',
    'CREATE TABLE IF NOT EXISTS epic_free_games (',
    '  id TEXT PRIMARY KEY,',
    '  title TEXT NOT NULL,',
    '  developer TEXT,',
    '  publisher TEXT,',
    '  original_price_usd REAL,',
    '  giveaway_start_date TEXT,',
    '  giveaway_end_date TEXT,',
    '  giveaway_type TEXT,',
    '  store_url TEXT,',
    '  claimed INTEGER DEFAULT 1',
    ');',
    '',
    'BEGIN TRANSACTION;',
  ];

  const escapeSQL = (val: string | number | undefined | null): string => {
    if (val === undefined || val === null) return 'NULL';
    if (typeof val === 'number') return String(val);
    return `'${String(val).replace(/'/g, "''")}'`;
  };

  for (const g of games) {
    const vals = [
      escapeSQL(g.id),
      escapeSQL(g.title),
      escapeSQL(g.developer || 'Unknown'),
      escapeSQL(g.publisher || 'Unknown'),
      escapeSQL(g.originalPrice || 0),
      escapeSQL(g.giveawayStartDate),
      escapeSQL(g.giveawayEndDate),
      escapeSQL(g.giveawayType),
      escapeSQL(g.storeUrl),
      '1',
    ].join(', ');
    lines.push(`INSERT OR REPLACE INTO epic_free_games (id, title, developer, publisher, original_price_usd, giveaway_start_date, giveaway_end_date, giveaway_type, store_url, claimed) VALUES (${vals});`);
  }

  lines.push('COMMIT;');
  lines.push('');

  downloadFile(lines.join('\n'), filename, 'application/sql;charset=utf-8');
}

/**
 * 5. Export as GitHub Markdown Table (.md)
 */
export function exportToMarkdown(games: GameData[], filename = 'epic-free-games-library.md') {
  const lines: string[] = [
    '# My Epic Games Free Library',
    '',
    `*Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} — **${games.length} titles** claimed*`,
    '',
    '| # | Title | Developer | Value (USD) | Free Giveaway Dates | Store Link |',
    '|---|---|---|---|---|---|',
  ];

  games.forEach((g, idx) => {
    const dev = g.developer && g.developer !== 'Unknown' ? g.developer : g.publisher || 'Unknown';
    const val = formatPrice(g.originalPrice || 0);
    const dateRange = formatDateRange(g.giveawayStartDate, g.giveawayEndDate);
    lines.push(`| ${idx + 1} | **${g.title}** | ${dev} | ${val} | ${dateRange} | [Store](${g.storeUrl}) |`);
  });

  lines.push('');
  downloadFile(lines.join('\n'), filename, 'text/markdown;charset=utf-8');
}
